version: '3.5'

services:

  db:
    image: postgres:16.1-alpine3.19
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    # ports:
    #   - 5432:5432

  backend:
    image: sivikgosh/backend_11:latest
    container_name: backend
    volumes:
      - static:/app/static/
      - media:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  frontend:
    image: natashasolntseva/funtech_frontend:v1.12
    container_name: frontend
    volumes:
      - frontend:/app/frontend/
    env_file:
      - ./.env
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - frontend:/var/html/frontend/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
    external: true
  static:
  media:
  frontend:
